"""Rebuild text masks: python tools/build-share-glyphs.py /path/to/NotoSansCJKkr-Regular.otf
Font source: https://github.com/notofonts/noto-cjk (SIL Open Font License).
Only rendered masks are checked in; no font or browser canvas is needed at request time.
"""
import base64, json, sys, zlib
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont
items = {'title':('나의 수학 나이는',28), 'brand':('몇 학년?',22), 'scoreLabel':('정답',20), 'timeLabel':('풀이 시간',20), 'footer':('당신은 몇 학년? 도전해보세요!',24)}
for level in range(1,11): items[f'grade{level}']=(f'초등 {level}학년' if level<=6 else f'중학교 {level-6}학년' if level<=9 else f'고등학교 {level-9}학년',64)
for c in '0123456789 /초': items[f'digit{c}']=(c,38)
out={}
for key,(text,size) in items.items():
 font=ImageFont.truetype(sys.argv[1],size)
 bbox=font.getbbox(text)
 width=max(1,int(font.getlength(text))+2)
 image=Image.new('L',(width,size+12),0)
 ImageDraw.Draw(image).text((0,-bbox[1]+4),text,font=font,fill=255)
 out[key]={'w':width,'h':size+12,'data':base64.b64encode(zlib.compress(image.tobytes(),9)).decode()}
Path('worker/share-glyphs.ts').write_text('// Generated by tools/build-share-glyphs.py; Noto Sans CJK, SIL OFL.\nexport const glyphs = '+json.dumps(out,ensure_ascii=False)+';\n')
